version: "3"

services:
  node:
    build:
      context: ./node
    container_name: node_app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - node_network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: node index.js
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_network

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: ngnix
    ports:
      - "8080:80"
    networks:
      - node_network
    depends_on:
      - node

networks:
  node_network:
    driver: bridge
